### ISSUE TITLE
lab3 failed

### ISSUE THREAD

**Issue by gigimushroom** [wqlin/mit-6.824-2018#1]
Test: one client (3A) ...
  ... Passed --  15.3  5   715  134
Test: many clients (3A) ...
2018/06/29 15:46:18.736652 get wrong value, key 3, wanted:
x 3 0 y
, got

exit status 1
FAIL    test/kvraft     17.756s

**Comment by wqlin** [comment]
@gigimushroom Sorry, i re-run lab3 for 10 times and didn't come across this error. Are you sure this result comes from running my implementation?

**Comment by gigimushroom** [comment]
Yes, I just repro it again.

and also:
D:\Computer Science\6.824\src\test\kvraft>go test -run 3B
Test: InstallSnapshot RPC (3B) ...
  ... Passed --  14.3  3   639   63
Test: snapshot size is reasonable (3B) ...
  ... Passed --  82.0  3  2426  800
Test: restarts, snapshots, one client (3B) ...
  ... Passed --  23.8  5   846  134
Test: restarts, snapshots, many clients (3B) ...
2018/06/30 13:55:24.604850 get wrong value, key 15, wanted:
x 15 0 y
, got

2018/06/30 13:55:24.604850 get wrong value, key 16, wanted:
x 16 0 y
, got

exit status 1
FAIL    test/kvraft     122.500s



Just download your zip, and retest it.

**Comment by wqlin** [comment]
@gigimushroom OK, which go version did you use?

**Comment by gigimushroom** [comment]
go1.7 windows/amd64

**Comment by wqlin** [comment]
@gigimushroom I suggest you upgrade to 1.9, that what the lab instruction suggests too. If possible, can you try install go 1.9, re-run the tests and report your results?

**Comment by gigimushroom** [comment]
Upgraded. same issues.

**Comment by wqlin** [comment]
@gigimushroom Are you using go 1.9.3?

**Comment by gigimushroom** [comment]
yes. 1.9.3
The problem is not the version of Go, it is bug in your system.
I just let you know this, in case you might care.
I don't care, since I have wrote my own.

**Comment by wqlin** [comment]
@gigimushroom I think i find the problem, this implementation doesn't work on windows. But i don't think that's a bug, since this lab is designed to run on linux. I suggest you migrate to linux too.
Please refer to section Software on [Lab 1](https://pdos.csail.mit.edu/6.824/labs/lab-1.html):

> You'll implement this lab (and all the labs) in Go. The Go web site contains lots of tutorial information which you may want to look at. We will grade your labs using Go version 1.9; you should use 1.9 too, though we don't know of any problems with other versions.
The labs are designed to run on Athena Linux machines with x86 or x86_64 architecture; uname -a should mention i386 GNU/Linux or i686 GNU/Linux or x86_64 GNU/Linux. You can log into a public Athena host with ssh athena.dialup.mit.edu. You may get lucky and find that the labs work in other environments, for example on some laptop Linux or OSX installations.
>

**Comment by gigimushroom** [comment]
Apologies, you are right. I think Go in windows has bugs, I switched to linux 1.9.3 and re-ran your code, no issues.

**Comment by wqlin** [comment]
@gigimushroom Yeap, glad to hear that. Have fun with 6.824.
